language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
env: 
  - TYPE=PYTHON PARAM=py34
  - TYPE=PYTHON PARAM=pep8
  - TYPE=ESLINT PARAM=./play/static/static/app/
script:
  - if [[ $TYPE == 'PYTHON' ]]; then tox -e $PARAM; fi
  - if [[ $TYPE == 'ESLINT' ]]; then eslint $PARAM; fi
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
install:
  -  if [[ $TYPE == 'PYTHON' ]]; then pip install tox; fi
  -  if [[ $TYPE == 'ESLINT' ]]; then npm install eslint; fi
